### ISSUE TITLE
Connection error with Storybook 7

### ISSUE THREAD

**Issue by JoostKersjes** [kalbeekatz/storybook-a11y-report#60]
This is the error I encountered:

```
$ npx storybook-a11y-report
ERROR! There is an error about connection: Evaluation failed: Error: extract called before initialization
    at StoryStore.extract (http://localhost:6006/sb-preview/runtime.js:40:11712)
    at StoryStore.raw (http://localhost:6006/sb-preview/runtime.js:40:13442)
    at ClientApi.raw (http://localhost:6006/sb-preview/runtime.js:72:408)
    at getStories (__puppeteer_evaluation_script__:18:45)
    at __puppeteer_evaluation_script__:29:17
    at new Promise (<anonymous>)
    at __puppeteer_evaluation_script__:1:8
```

Not sure if this is actually related to the Storybook 7, but I presumed that to be the case, since it is an issue with the connection.

The "Accessibility" tab in Storybook itself works as expected.

Possibly relevant package versions in my project:

- `"vue": "3.3.4"`
- `"@storybook/addon-a11y": "7.0.15"`
- `"@storybook/vue3-vite": "7.0.15"`
- `"storybook": "7.0.15"`
- `"typescript": "5.0.4"`
- `"vite": "4.3.8"`

Here is some more `envinfo`:

```
$ npx envinfo --system --binaries

  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
    Memory: 7.98 GB / 15.31 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.0.0 - ~/.nvm/versions/node/v20.0.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v20.0.0/bin/npm
```

**Comment by kalbeekatz** [comment]
@JoostKersjes
Thanks for reporting.
I have resolved the error that occurred in Storybook v7. Please try the new version.
